
language: node_js
node_js: 8

cache:
  directories:
    - blog/node_modules

install:
  - yarn --cwd blog

script:
  - hexo --cwd blog g

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: blog/public
  github-token: $GH_TOKEN
  on:
    branch:
      - source

branches:
  only:
    - source
