# Header

menu:
  主页: /
  归档: /collection/
  分类: /categories/
  留言: /messages/

# SubNav
subnav:
  mail: "http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=whucstao@qq.com"
  github: "https://github.com/CS-Tao"
  rss: /atom.xml
  #zhihu: "https://www.zhihu.com/people/tao-chun-sheng-21/activities"
  #weibo: "http://weibo.com/tcs990296951"
  #google: "https://plus.google.com/115901576244995527191"
  #twitter: "https://twitter.com/TaoChengSheng"
  #linkedin: "https://www.linkedin.com/in/%E6%98%A5%E7%94%9F-%E9%99%B6-9917b3148/"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #facebook: "#"


# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: '查看更多'
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: true
# 是否在新窗口打开链接
open_in_new: true

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 1
# 打赏wording
reward_wording: '纯属娱乐'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /blog/img/alipayimg.jpg
# 微信二维码图片地址
weixin: /blog/img/wechatimg.jpg

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: false
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
google_analytics: UA-104910484-1
baidu_analytics: 60c849aef33194f2884736dfb3f0b518
favicon: /blog/favicon.png

#你的头像url
avatar: /blog/img/avatar.png

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment；6、livere；7、友言
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: GIS-Hacker     #你的 GitHub ID
gitment_repo: 'CS-Tao.github.io-comments'          #存储评论的 repo
gitment_oauth:
  client_id: 'afb484520f02435d9ef4'           #client ID
  client_secret: 'cec4ead127d888767428def9dd8d5b048673ac5b'       #client secret

#6、来必力
#livere: MTAyMC8zMzI4OS85ODQ2
livere: false

#7、友言
#uyan: 2155253
uyan: false

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友情链接'
  aboutme: false

aboutme: <p align="center">大三学生<br><br>现就读与武汉大学</p>

friends:
  Chaogui Kang: "http://urbancolab.org/"
  HPDell: "https://hpdell.github.io/"
  Wuchen: "https://mysticfalls0709.github.io/"
  blablaxiaomoxian: "https://blablaxiaomoxian.github.io/"

# 不蒜子网站计数设置
# http://ibruce.info/2015/04/04/busuanzi/
#visit_counter:
#  on: true
#  site_visit: 网站访客数
#  page_visit: false